CC = g++
CFLAGS = -O3

default:
	$(CC) $(CFLAGS) barnes_ref.cpp data_io.cpp -o barnes_algorithm
	$(CC) $(CFLAGS) garbrecht_ref.cpp data_io.cpp -o garbrecht_algorithm
	$(CC) $(CFLAGS) generate_square_grid.cpp -o generate_square_grid
