CC = g++
CFLAGS = -O3

default:
	$(CC) $(CFLAGS) barnes_ref.cpp             -o barnes_algorithm.exe
	$(CC) $(CFLAGS) garbrecht_ref.cpp          -o garbrecht_algorithm.exe
	$(CC) $(CFLAGS) generate_square_grid.cpp   -o generate_square_grid.exe
